Standardize and refactor the API handlers
loopline-systems/closeio-api-wrapper pull request #92
Opened 2018-08-31 08:00 UTC by ste93cry

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | yes
| Tests pass?   | yes
| License       | MIT

This PR is an initial refactoring of the classes that handle the APIs by exposing common methods to interact with each resource type. I've tried to standardize the naming of those methods, added typehints and docblocks so that everything is well documented and clear. There are some BC breaks (e.g. the delete methods do not return `boolean` anymore). I've also added the deprecation warning to all methods that should be removed in a later release

2018-09-17 04:48 UTC, mavimo requested changes
@ste93cry we should discuss the signature of `delete` method in repos and changes reported as comment in this PR.

2018-09-17 04:48 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CustomFieldApi.php
> +    public function delete(string $contactId): void
Maybe do you mean `customFieldId` instead of `contactId`?

2018-09-17 04:48 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CustomFieldApi.php
> +    public function delete(string $contactId): void
I'm not sure we should use a string to indicate the custom field to remove, maybe we should consider to use a `Contact` model that we will use to delete it, than the public API will be something like:

```
public function get(string $customFieldId): CustomField;
public function create(CustomField $customField): void;
public function update(CustomField $customField): void;
public function delete(CustomField $customField): void;
```

2018-09-17 04:48 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +    private const MAX_ITEMS_PER_REQUEST = 50;
I can't find any info about max limit on this resource from API docs, can you address me to the docs that indicate 50 as the limit?

2018-09-17 04:48 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +            'delete-note' => '/activity/note/[:id]/',
Maybe we can consider to split this API into:

 - `CallActivityApi`
 - `EmailActivityApi`
 - `NoteActivityApi`
 - `SmsActivityApi`

@ste93cry what do you think?

2018-09-17 04:48 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ContactApi.php
> +    public function delete(string $contactId): void
See previous note about the argument of delete method.

2018-09-19 07:38 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +    private const MAX_ITEMS_PER_REQUEST = 50;
I chose the limit arbitrarily based on the fact that the objects to be hydrated were neither few nor too many. I've raised it to 100 items per request. This is not anyway an hard limit but just the default value, so you can override it manually in each API call to get a list of items

2018-09-19 10:19 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/CustomFieldApi.php
> +    public function delete(string $contactId): void
In terms of consistency with the other methods I agree with you that it makes more sense to accept as input an object representing the resource to delete, although this makes harder to delete something without hydrating the model first (at least with the ID). Let's go with the way you suggest btw

2018-09-19 10:22 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +            'delete-note' => '/activity/note/[:id]/',
I've done it as it's indeed clearer and permits to develop further each single API handler

2018-09-19 22:29 UTC, mavimo requested changes

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/NoteActivityApi.php
> +    public const MAX_ITEMS_PER_REQUEST = 100;
We mis use of public/private const for `MAX_ITEMS_PER_REQUEST`, I'll go for private on all API since is an internal information and uniformate it on all API to improve code consistency, @ste93cry what's your opinion?

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/SmsActivityApi.php
> +    public const MAX_ITEMS_PER_REQUEST = 100;
We mis use of public/private const for `MAX_ITEMS_PER_REQUEST`, I'll go for private on all API since is an internal information and uniformate it on all API to improve code consistency, @ste93cry what's your opinion?

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/TaskApi.php
> +    public const MAX_ITEMS_PER_REQUEST = 100;
We mis use of public/private const for `MAX_ITEMS_PER_REQUEST`, I'll go for private on all API since is an internal information and uniformate it on all API to improve code consistency, @ste93cry what's your opinion?

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/LeadApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
I'm not sure on `getAll` naming.
Using `getAll` let's suppose we are going to get all leads we store on close.io, but this is not true, we will return only the first batch, to fetch all we should fetch a list of batch untile there are no more results.

IMHO we should consider to use something like `getBatch` / `getChunk` / `find` / `...` (that also give more sense to `offset`/`limit` parameters), to explicit what we are going to do here. `getAll` should be used only if we internally iterate on the resultset and return a real list with all information. Just to be clear I'm NOT suggesting to implement it using an internal loop that I think should be a bad approach since can generate timeout/ratelimit exception & c if bad used. If some user will need it can be easily added but -at last- will not use this naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CallActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ContactApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CustomFieldApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/EmailActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/LeadStatusApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/NoteActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/OpportunityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/OpportunityStatusApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/SmsActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/TaskApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-19 22:29 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/UserApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $fields = []): array
See previous comment on function naming.

2018-09-20 08:35 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/NoteActivityApi.php
> +    public const MAX_ITEMS_PER_REQUEST = 100;
Initially they all where `private` but I changed the visibility of the constant in the `*ActivityApi` classes because I needed to use them in the main `ActivityApi` class. I've now switched back to `private` and used `ActivityApi::MAX_ITEMS_PER_REQUEST` in all methods of that class instead of the constant of each API handler as their value is anyway the same

2018-09-20 08:36 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
`find` seems appropriate for something that search things and this is not our case even though we support filtering the results. `list` seems appropriate to me as it means that we're going to list a set of records, filtered and paginated

2018-09-20 08:52 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/ActivityApi.php
> +    public function getAll(int $offset = 0, int $limit = self::MAX_ITEMS_PER_REQUEST, array $filters = [], array $fields = []): array
@ste93cry `list` sound good to me!

2018-09-20 08:55 UTC, mavimo approved these changes

2018-09-20 09:11 UTC, merged