Use Httplug as HTTP transport layer
loopline-systems/closeio-api-wrapper pull request #93
Opened 2018-09-03 13:08 UTC by ste93cry

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

With this PR I've introduced the support for Httplug as transport layer. In this way we don't have to maintain our own implementation of an HTTP client (cURL in the simplest case) and we can offer more flexibility to users of this library leaving to them the choice of what they prefer to use to send HTTP requests (even Guzzle if they want).

2018-09-27 13:49 UTC, mavimo requested changes
We have some issue on test, and we should include some more doc on hot to use this new feature.
I really like to externalise transport layer from lib but we should be sure that all user should be able to use it without issue.

2018-10-03 10:19 UTC, mavimo requested changes

2018-10-03 10:19 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CallActivityApi.php
> +        throw new ResourceNotFoundException();
We should return `ResourceNotFoundException` only for `$response->getHttpStatusCode()`, all other status should be `BadApiRequestException`.

PS: propagate the same comment on all other `get` methods.

2018-10-03 10:19 UTC, mavimo commented on src/LooplineSystems/CloseIoApiWrapper/Api/CallActivityApi.php
> +        if (200 === $response->getHttpStatusCode() && !$response->isError()) {
I prefer to keep `hasError` instead of using `isError`, please revert renaming.

2018-10-03 13:45 UTC, ste93cry commented on src/LooplineSystems/CloseIoApiWrapper/Api/CallActivityApi.php
> +        throw new ResourceNotFoundException();
I disagree that all response status codes different from 400 should throw the `BadApiRequestException`. I've made some adjustment to the code so that we throw a `CloseIoResponseException` in all cases not covered by a more specific exception

2018-10-15 05:54 UTC, mavimo approved these changes

2018-10-15 05:54 UTC, merged